[Log]
Level = "debug"
Outputs = ["stdout"]

[SyncDB]
Database = "postgres"
User = "test_user"
Password = "test_password"
Name = "test_db"
Host = "zkevm-bridge-db"
Port = "5432"
MaxConns = 20

[ClaimTxManager]
FrequencyToMonitorTxs = "1s"
PrivateKey = {Path = "/pk/keystore.claimtxmanager", Password = "testonly"}

[Etherman]
L1URL = "http://159.135.192.196:8545"
L2URLs = ["http://zkevm-json-rpc:8123"]

[Synchronizer]
SyncInterval = "1s"
SyncChunkSize = 100

[BridgeController]
Store = "postgres"
Height = 32

[BridgeServer]
GRPCPort = "9090"
HTTPPort = "8080"
CacheSize = 100000
DefaultPageLimit = 25
MaxPageLimit = 100
BridgeVersion = "v1"
    [BridgeServer.DB]
    User = "test_user"
    Password = "test_password"
    Name = "test_db"
    Host = "zkevm-bridge-db"
    Port = "5432"
    MaxConns = 20

[NetworkConfig]
GenBlockNumber = 19384
PoEAddr = "0x2De72e7E01AA2E715aEbd211169EbE14Dfdd4f7c"
BridgeAddr = "0xDa99b77Df6631d5695E86e00e62aeBE53A673f57"
GlobalExitRootManAddr = "0xbC06921042219DC43E98dC520dD624C46CfeCd9d"
MaticAddr = "0x359b74eBC1177a01F4737BcEB6a90123a867b93A"
L2BridgeAddrs = ["0x5f0f22E631d742E4aEC7F6eeCf11066524D0aEdB"]
L1ChainID = 51178 